"""
normalize_linkedin_csv.py

Standalone normalization tuning harness for LinkedIn-scraped job CSVs.
Iterate heuristics here before promoting changes into backend/scraping/.

Usage:
    python normalize_linkedin_csv.py --in in.csv --out out.csv
    python normalize_linkedin_csv.py --in in.csv --out out.csv --drop-noise

Requires concepts.json (generated by dump_concepts.py) in the same directory.
If concepts.json is missing, run:
    python dump_concepts.py
"""

import argparse
import csv
import json
import re
from pathlib import Path

# ─── Fuzzy matching (thefuzz must be installed: pip install thefuzz) ──────────
try:
    from thefuzz import fuzz
    _FUZZY_AVAILABLE = True
except ImportError:
    _FUZZY_AVAILABLE = False

# =============================================================================
# SKILL SYNONYMS
# Kept in sync with backend/scraping/matcher.py — full 171-entry map.
# Canonical form is on the RIGHT side of each entry.
# =============================================================================
SKILL_SYNONYMS = {
    # JavaScript ecosystem
    "reactjs": "react",
    "react.js": "react",
    "react js": "react",
    "vuejs": "vue",
    "vue.js": "vue",
    "vue js": "vue",
    "angularjs": "angular",
    "angular.js": "angular",
    "nodejs": "node.js",
    # bare "node" excluded — too common in distributed systems prose
    "expressjs": "express.js",
    # bare "express" excluded — common English word
    "nextjs": "next.js",
    # bare "next" intentionally excluded — too common an English word (false positives)
    "typescript": "typescript",
    # "ts" excluded — often means "timestamp" in job descriptions
    "javascript": "javascript",
    # "js" excluded — usually written in full in job descriptions
    "es6": "javascript",
    "es6+": "javascript",

    # Python ecosystem
    "python3": "python",
    # "py" excluded — rarely standalone in prose
    "pytorch": "pytorch",
    "torch": "pytorch",
    "tensorflow": "tensorflow",
    # "tf" excluded — ambiguous (TensorFlow vs. Terraform abbreviation)
    "scikit-learn": "scikit-learn",
    "sklearn": "scikit-learn",
    "scikit learn": "scikit-learn",
    "pandas": "pandas",
    "numpy": "numpy",
    "np": "numpy",
    "fastapi": "fastapi",
    "fast api": "fastapi",
    "django": "django",
    "flask": "flask",

    # Databases
    "postgresql": "postgresql",
    "postgres": "postgresql",
    "psql": "postgresql",
    "mysql": "mysql",
    "mongodb": "mongodb",
    "mongo": "mongodb",
    "redis": "redis",
    "elasticsearch": "elasticsearch",
    "elastic": "elasticsearch",
    "dynamodb": "dynamodb",
    "dynamo": "dynamodb",

    # Cloud & DevOps
    "kubernetes": "kubernetes",
    "k8s": "kubernetes",
    "docker": "docker",
    "docker-compose": "docker",
    "terraform": "terraform",
    "cloudformation": "cloudformation",
    "cfn": "cloudformation",
    "aws": "aws",
    "amazon web services": "aws",
    "azure": "azure",
    "microsoft azure": "azure",
    "gcp": "gcp",
    "google cloud": "gcp",
    "google cloud platform": "gcp",
    "jenkins": "jenkins",
    "github actions": "github actions",
    "gh actions": "github actions",
    "gitlab ci": "gitlab ci",
    "circleci": "circleci",
    "circle ci": "circleci",
    "ansible": "ansible",
    "helm": "helm",
    "argocd": "argocd",
    "argo cd": "argocd",

    # Languages
    "golang": "go",
    "go lang": "go",
    "go-lang": "go",
    "rust lang": "rust",
    "rustlang": "rust",
    "c++": "c++",
    "cpp": "c++",
    "c#": "c#",
    "csharp": "c#",
    "c sharp": "c#",
    "dotnet": ".net",
    ".net core": ".net",
    ".net framework": ".net",
    "java": "java",
    "kotlin": "kotlin",
    "swift": "swift",
    "ruby": "ruby",
    "php": "php",
    "scala": "scala",
    "r": "r",   # kept — word-boundary regex prevents most false positives

    # Mobile
    "swiftui": "swiftui",
    "react native": "react native",
    "reactnative": "react native",
    "flutter": "flutter",
    "ios": "ios",
    "android": "android",
    "jetpack compose": "jetpack compose",

    # Security
    "owasp": "owasp",
    "owasp top 10": "owasp",
    "penetration testing": "penetration testing",
    "pen testing": "penetration testing",
    "pentest": "penetration testing",
    "pentesting": "penetration testing",
    "burp suite": "burp suite",
    "burpsuite": "burp suite",
    "nmap": "nmap",
    "metasploit": "metasploit",
    "wireshark": "wireshark",

    # Data & ML
    "machine learning": "machine learning",
    "ml": "machine learning",
    "deep learning": "deep learning",
    # "dl" excluded — ambiguous in prose
    "natural language processing": "nlp",
    "nlp": "nlp",
    "computer vision": "computer vision",
    # "cv" excluded — means "curriculum vitae" in job context
    "llm": "llm",
    "llms": "llm",
    "large language model": "llm",
    "large language models": "llm",
    "huggingface": "huggingface",
    "hugging face": "huggingface",
    "transformers": "transformers",
    "generative ai": "generative ai",
    "gen ai": "generative ai",
    "ai": "ai",
    "artificial intelligence": "ai",
    "microservices": "microservices",
    "microservice": "microservices",
    "distributed systems": "distributed systems",
    "system design": "system design",
    "rag": "rag",
    "retrieval augmented generation": "rag",
    "vector database": "vector database",
    "vector db": "vector database",
    "fine-tuning": "fine-tuning",
    "fine tuning": "fine-tuning",

    # Data Visualization
    "tableau": "tableau",
    "power bi": "power bi",
    "powerbi": "power bi",
    "looker": "looker",
    "d3.js": "d3.js",
    "d3": "d3.js",
    "superset": "superset",
    "apache superset": "superset",
    "metabase": "metabase",
    "dbt": "dbt",

    # General
    "restful api": "rest api",
    "restful apis": "rest api",
    "rest api": "rest api",
    "rest apis": "rest api",
    # bare "rest" excluded — extremely common English word
    "graphql": "graphql",
    "grpc": "grpc",
    "git": "git",
    "github": "github",
    "gitlab": "gitlab",
    "bitbucket": "bitbucket",
    "jira": "jira",
    "confluence": "confluence",
    "agile": "agile",
    "scrum": "scrum",
    "kanban": "kanban",
    "ci/cd": "ci/cd",
    "cicd": "ci/cd",
    "continuous integration": "ci/cd",
    "continuous deployment": "ci/cd",
    "linux": "linux",
    "sql": "sql",
    "nosql": "nosql databases",
    "nosql databases": "nosql databases",
    "bash": "bash",
    "shell script": "bash",
    "shell scripting": "bash",
    # bare "shell" excluded — matches "shell company", "shell out" etc.
    "apache kafka": "kafka",
    "kafka": "kafka",
    "apache spark": "spark",
    "pyspark": "spark",
    "spark": "spark",
    "airflow": "airflow",
    "apache airflow": "airflow",
    "prometheus": "prometheus",
    "grafana": "grafana",
    "nginx": "nginx",
    "redis cache": "redis",
}

# =============================================================================
# JOB TITLES — stripped from skills output (they are roles, not skills)
# Sourced from backend/knowledge_graph/config/jobs.py JOBS list.
# =============================================================================
JOB_TITLES = {
    "front-end engineer",
    "back-end engineer",
    "full-stack engineer",
    "mobile engineer (android)",
    "mobile engineer (ios)",
    "mobile engineer",
    "systems engineer",
    "game developer",
    "security analyst",
    "penetration tester",
    "security engineer",
    "cloud security engineer",
    "soc analyst",
    "application security engineer",
    "grc analyst",
    "machine learning engineer",
    "data scientist",
    "ai engineer",
    "nlp engineer",
    "computer vision engineer",
    "research scientist",
    "bi developer",
    "data visualization engineer",
    "analytics engineer",
    "reporting analyst",
    "cloud infrastructure engineer",
    "cloud architect",
    "site reliability engineer",
    "platform engineer",
    "technical project manager",
    "agile project manager",
    "program manager",
    "scrum master",
    "devops engineer",
    "ci/cd engineer",
    "infrastructure as code engineer",
    "release engineer",
    "containerization engineer",
    # common scraper variants
    "automation engineer",
    "devops",
    "application security",
    "platform engineer",
    "technical product manager",
    "product manager",
    "engineering manager",
    "staff engineer",
    "principal engineer",
    "solutions architect",
}

# =============================================================================
# NOISE ROW DETECTION
# =============================================================================
NOISE_PATTERNS = [
    "LINKEDIN IS BETTER ON THE APP",
    "JOIN LINKEDIN",
    "AGREE & JOIN",
    "PASSWORD (6+ CHARACTERS)",
    "OPEN THE APP",
    "DON'T HAVE THE APP",
    "GET IT IN THE MICROSOFT STORE",
    "PRIVACY POLICY",
    "USER AGREEMENT",
]

# =============================================================================
# BLOCKED CONCEPTS — always rejected regardless of source
# Generic English words that appear in graph but are far too ambiguous to
# extract blindly from free text.
# =============================================================================
BLOCKED_CONCEPTS = {
    # Graph noise / meta nodes
    "MAN",
    "CAT",
    "VISION & MISSION",
    "SECURITY SKILLS AND KNOWLEDGE",
    "PENETRATION TESTING RULES OF ENGAGEMENT",
    "AI IN PRODUCT MGMT.",
    "CLOUD-NATIVE ML SERVICES",
    "DATA REPLICATION",
    "HR",
    "BOX",
    "BUS",
    "AHA",          # product tool "Aha!" but too short/ambiguous
    # High-frequency false positives — common English words that happen to be
    # in the graph but match job-description prose rather than skills:
    "TEAMS",        # matches "work with teams", not "Microsoft Teams"
    "LOCATION",     # job location field leakage
    "HYBRID",       # work arrangement, not a tech skill
    "PUBLIC",       # "public speaking", "public cloud" ambiguous
    "LEGAL",        # compliance prose
    "STAKEHOLDERS", # generic management prose
    "DISCOVERY",    # "service discovery" is too ambiguous without qualifier
    "NETWORK",      # too generic; "networking" concept still extractable via graph
    "FRAMEWORKS",   # never standalone — always "X frameworks"
    "SERVICES",     # too generic
    "COMPONENTS",   # too generic
    "COMPLIANCE",   # process word, not a skill
    "MONITORING",   # too generic alone (Prometheus/Grafana should match instead)
    "DEVELOPMENT",  # too generic
    "INTERNET",     # too generic
    "GROWTH",       # marketing/business prose
    "VIEWS",        # UI or SQL context ambiguous
    "BASE",         # too generic
    "FLOW",         # too generic
    "ACTIVITY",     # too generic
    "CLOSURES",     # JS concept but too rare/ambiguous
    "CONCURRENCY",  # valid concept but matches too broadly
    "CONTAINERS",   # should match via "docker"/"kubernetes" synonyms
    "WINDOWS",      # OS vs Windows as software ambiguous
    "TESTING",      # too generic — specific testing skills preferred
    "CACHING",      # too generic
    "BUTTONS",      # UI element, not a skill
    # Graph concepts that are common English words / match prose, not skills:
    "REST",         # use "restful api" / "rest api" instead
    "INSTALLING",   # action word, not a skill
    "PRIVATE",      # adjective, not a skill
    "MANAGEMENT",   # too generic
    "BUSINESS",     # not a skill
    "NARRATIVE",    # not a skill
    "MATURITY",     # not a skill
    "PROPOSITION",  # not a skill
    "PREPARATION",  # not a skill
    "DECLINE",      # not a skill
    "CODING",       # too generic (language-specific skills preferred)
    "SELECTION",    # not a skill
    "STAR",         # not a skill
    "STATEMENT",    # not a skill
    "TREND",        # not a skill
    "TIMEFRAME",    # not a skill
    "INTRODUCTION", # not a skill
    "AVAILABILITY", # too generic
    "CAPABILITIES", # too generic
    "IDENTIFICATION", # too generic
    "EXECUTION",    # too generic
    "DISTRIBUTION", # too generic
    "MEDIA",        # too generic
    "GROUPS",       # too generic
    "CONSTRAINT",   # too generic
    "BASELINE",     # not a skill
    "TROUBLESHOOTING",  # too generic
    "VALIDATION",   # too generic
    "RELATIVE",     # not a skill
    "TARGET",       # not a skill
    "FRAME",        # not a skill
    "SWITCH",       # hardware device OR language construct — too ambiguous
    "RING",         # not a skill
    "ROUTER",       # too generic alone (specific routing tools preferred)
    "MESH",         # too generic
    "RETRO",        # too generic (Retrospective? Retro styling?)
    "NAVIGATION",   # too generic
    "PARSING",      # too generic
    "HASHING",      # valid concept but too broad
    "PATCHING",     # process word
    "ERADICATION",  # incident response step, not a tool/skill
    "CONTAINMENT",  # incident response step
    "RECOVERY",     # too generic
    "RECONNAISSANCE", # security step, very generic
    "STEPPING",     # not a skill
    "IMPERSONATION", # not a skill
    "PHISHING",     # attack type, not a defender skill
    "SMISHING",     # attack type
    "WHALING",      # attack type
    "TAILGATING",   # physical security, too generic
    "SPOOFING",     # attack type
    "SINKHOLES",    # too niche/generic
    "SANDBOXING",   # valid but too generic
    "OBFUSCATION",  # too generic
    "SALTING",      # too generic
    "INTERPERSONAL", # soft skill, not a tech skill
    "BACKPRESSURE", # too technical/generic
    "LOADSHIFTING", # too generic
    "THROTTLING",   # too generic
    "NORMALIZATION",# too generic
    "LINEARIZATION", # not a standard skill
    "TABS",         # matches "browser tabs" in prose, not Android Tabs widget
    "HEAD",         # matches "<head>" in HTML or "head of engineering" in prose
    "KEY SKILLS",   # section header leaking from job post formatting
    "HTTPS",        # URL protocol matching job post boilerplate links
    "HTTP",         # URL protocol — 103 hits in Jobright boilerplate
    "PAYMENTS",     # Apple/Stripe domain word, not a transferable skill
    "STORAGE",      # too generic — 72 hits; specific tools (Redis, S3, etc.) preferred
}

# Pre-built set of all canonical values in SKILL_SYNONYMS for O(1) lookup.
# Skills that normalize to one of these are considered "synonym-validated"
# and bypass graph matching — the synonym map itself is the trusted allowlist.
SYNONYM_CANONICALS: set[str] = set(SKILL_SYNONYMS.values())

SHORT_SKILL_ALLOWLIST = {
    "AI", "ML", "NLP", "AWS", "GCP", "SQL", "API", "BI", "SOC", "IAM",
    "CI/CD", "C++", "C#", "CSS", "HTML", "PHP", "DNS", "VPN", "SSH",
    "JWT", "SSO", "XSS", "CDN", "MVC", "OOP", "SDK", "IDE", "CLI",
    "VPC", "EC2", "S3", "RDS", "ECS", "EKS", "ACL", "TLS", "SSL",
    "TCP", "UDP", "IP", "GO", "R",
}

# =============================================================================
# SKILL VALIDATION THRESHOLDS
# =============================================================================
FUZZY_MATCH_THRESHOLD = 85   # thefuzz ratio threshold for graph validation
MAX_SKILL_LENGTH = 60        # reject anything longer (likely a sentence fragment)
MAX_SKILLS_PER_ROW = 35


# =============================================================================
# CONCEPT VOCABULARY LOADER
# =============================================================================
def load_concepts(script_dir: Path) -> tuple[list[str], list[str]]:
    """
    Load extractable and validate_only concept lists from concepts.json.
    Returns (extractable, all_concepts) where all_concepts = extractable + validate_only.
    """
    concepts_path = script_dir / "concepts.json"
    if not concepts_path.exists():
        print(
            "WARNING: concepts.json not found. Run 'python dump_concepts.py' first.\n"
            "         Falling back to synonym-only vocabulary (reduced coverage)."
        )
        return [], []

    with open(concepts_path, encoding="utf-8") as f:
        data = json.load(f)

    extractable = data.get("extractable", [])
    validate_only = data.get("validate_only", [])
    all_concepts = extractable + validate_only

    generated_from = data.get("generated_from", "unknown")
    counts = data.get("counts", {})
    print(
        f"Loaded concepts from {generated_from}: "
        f"{counts.get('extractable', len(extractable))} extractable, "
        f"{counts.get('validate_only', len(validate_only))} validate-only"
    )
    return extractable, all_concepts


# =============================================================================
# VOCABULARY BUILDER
# =============================================================================
def build_vocab(extractable_concepts: list[str]) -> set[str]:
    """
    Build the full extraction vocabulary:
      - all synonym keys and canonical values from SKILL_SYNONYMS
      - all extractable concept names (lowercased)
    Returns a set of lowercase strings for regex matching.
    """
    vocab = set()

    # Synonym keys and canonical values
    vocab.update(SKILL_SYNONYMS.keys())
    vocab.update(SKILL_SYNONYMS.values())

    # Extractable concepts (lowercased)
    for name in extractable_concepts:
        vocab.add(name.strip().lower())

    # Remove anything too short or blocked
    cleaned = set()
    for term in vocab:
        t = term.strip()
        if len(t) < 2:
            continue
        if t.upper() in BLOCKED_CONCEPTS:
            continue
        cleaned.add(t)

    return cleaned


# =============================================================================
# NORMALIZATION HELPERS
# =============================================================================
def normalize_skill(skill: str) -> str:
    """Apply synonym map, return canonical lowercase form."""
    if not skill:
        return ""
    s = skill.strip().lower()
    return SKILL_SYNONYMS.get(s, s)


def parse_skills(value) -> list[str]:
    """Parse pipe-separated or bracket-list skill strings."""
    if value is None:
        return []
    text = str(value).strip()
    if not text:
        return []
    if "|" in text:
        return [p.strip() for p in text.split("|") if p.strip()]
    if text.startswith("[") and text.endswith("]"):
        inner = text[1:-1].strip()
        if not inner:
            return []
        return [p.strip().strip('"').strip("'") for p in inner.split(",") if p.strip()]
    return [text]


def company_self_tokens(company: str) -> set[str]:
    """
    Build a set of lowercase tokens from the company name that should not
    appear as skills on that company's own job listings.

    Strategy: split on common separators, keep tokens >= 4 chars
    (avoids blocking single-letter or tiny words like "at", "the", "inc").
    Also include the full lowercased company name.

    Examples:
        "Notion"              → {"notion"}
        "Apple"               → {"apple"}
        "The New York Times"  → {"new york times", "york", "times"}
        "Nightfall AI"        → {"nightfall"}   (AI is in SHORT_SKILL_ALLOWLIST so keep it)
    """
    if not company:
        return set()
    tokens = set()
    name_lower = company.strip().lower()
    # Remove common legal suffixes that are never skills
    for suffix in (" inc", " llc", " ltd", " corp", " co", " group", " solutions",
                   " consulting", " technologies", " technology", " services",
                   " partners", " labs", " studio", " studios"):
        name_lower = name_lower.replace(suffix, "")
    name_lower = name_lower.strip()
    tokens.add(name_lower)
    # Individual words >= 4 chars
    for word in re.split(r"[\s\-_,&()./]+", name_lower):
        word = word.strip()
        if len(word) >= 4:
            tokens.add(word)
    return tokens


def is_noise_row(company: str, job: str, desc: str = "") -> bool:
    """
    Detect scraper-artifact rows that contain no real job data.
    Checks both the company/job fields and the description text.
    """
    blob = f"{company} {job}".upper()
    if any(p in blob for p in NOISE_PATTERNS):
        return True
    # Also catch rows where the description IS the LinkedIn login wall
    desc_upper = desc.upper()
    if any(p in desc_upper for p in NOISE_PATTERNS):
        return True
    return False


def is_job_title(skill_upper: str) -> bool:
    """Return True if this string is a role/job title, not a skill."""
    return skill_upper.lower() in JOB_TITLES


def is_valid_skill_label(skill: str) -> bool:
    """
    Gate on a candidate skill string before it enters the output.
    Returns False for:
      - empty or blank
      - blocked concepts
      - salary/compensation fragments
      - numeric fragments
      - too-long strings (likely sentence fragments)
      - pure punctuation / stray dashes
      - job title strings (roles, not skills)
    """
    if not skill:
        return False
    s = skill.strip()
    su = s.upper()

    if not s:
        return False
    if su in BLOCKED_CONCEPTS:
        return False
    if is_job_title(su):
        return False

    # Too long
    if len(s) > MAX_SKILL_LENGTH:
        return False

    # Compensation / numeric noise
    if re.search(r"\d", s):
        # Allow short acronyms with numbers like "3D", "Web3", "iOS"
        if len(s) > 6:
            return False
    if any(tok in su for tok in ["SALARY", "$", "CHARACTERS", "HOURS", "YEARS"]):
        return False

    # Short label filter
    if len(su) <= 2 and su not in SHORT_SKILL_ALLOWLIST:
        return False
    if len(su) == 3 and su not in SHORT_SKILL_ALLOWLIST and not su.isupper():
        return False

    # Stray punctuation
    if s.startswith("-") or s.endswith("-"):
        return False
    if s in {".", ",", ":", ";", "/", "|"}:
        return False

    return True


# =============================================================================
# FUZZY GRAPH VALIDATION
# =============================================================================
def build_concept_lookup(all_concepts: list[str]) -> dict[str, str]:
    """
    Build a dict mapping lowercase concept name -> original-case concept name
    for O(1) exact lookup and fuzzy fallback.
    """
    return {c.lower(): c for c in all_concepts}


def validate_against_graph(
    skill_lower: str,
    concept_lookup: dict[str, str],
    all_concepts_lower: list[str],
) -> str | None:
    """
    Try to match a skill string against the known concept vocabulary.
    Returns the canonical concept name if matched, else None.

    Strategy:
      0. Synonym-canonical shortcut — if the skill (or its synonym-normalized
         form) is a canonical value in SKILL_SYNONYMS, trust it directly.
         The synonym map is a curated allowlist; no graph hit needed.
      1. Exact lowercase match against graph concepts
      2. Synonym-normalize then exact match
      3. Fuzzy match (thefuzz, threshold FUZZY_MATCH_THRESHOLD)
    """
    # 0. Synonym-canonical shortcut
    if skill_lower in SYNONYM_CANONICALS:
        return skill_lower.upper()
    normed = normalize_skill(skill_lower)
    if normed in SYNONYM_CANONICALS:
        return normed.upper()

    # 1. Exact
    if skill_lower in concept_lookup:
        return concept_lookup[skill_lower]

    # 2. Synonym → exact
    if normed in concept_lookup:
        return concept_lookup[normed]

    # 3. Fuzzy fallback
    if _FUZZY_AVAILABLE and all_concepts_lower:
        best_score = 0
        best_concept = None
        for candidate_lower in all_concepts_lower:
            score = fuzz.ratio(skill_lower, candidate_lower)
            if score > best_score:
                best_score = score
                best_concept = candidate_lower
        if best_score >= FUZZY_MATCH_THRESHOLD and best_concept:
            return concept_lookup.get(best_concept, best_concept)

    return None


# =============================================================================
# CORE EXTRACTION
# =============================================================================
def extract_skills_from_text(text: str, vocab: set[str]) -> list[str]:
    """
    Scan free text for vocab terms using regex word-boundary matching.
    Returns a list of canonical (lowercased, synonym-normalized) skill strings.
    """
    if not text:
        return []

    content = text.lower()
    found = set()

    for term in vocab:
        # Use word-boundary regex; allow for punctuation breaks around the term
        pattern = r"(?<![a-z0-9\-\.])" + re.escape(term) + r"(?![a-z0-9\-\.])"
        if re.search(pattern, content):
            canonical = normalize_skill(term)
            if canonical:
                found.add(canonical)

    return sorted(found)


# =============================================================================
# ROW NORMALIZER
# =============================================================================
def normalize_row(
    row: dict,
    vocab: set[str],
    concept_lookup: dict[str, str],
    all_concepts_lower: list[str],
) -> dict:
    company = (row.get("company_name") or row.get("company") or "").strip()
    job = (row.get("job_name") or row.get("job") or "").strip()
    desc = (row.get("description") or "").strip()
    qualifications_raw = row.get("qualifications") or row.get("skills") or ""

    # Parse the qualifications column (usually the matched job title from scraper)
    base_skills_raw = parse_skills(qualifications_raw)

    # Normalize base skills but immediately flag & strip job title strings
    base_skills_clean = []
    for s in base_skills_raw:
        norm = normalize_skill(s).strip()
        if not norm:
            continue
        # Keep only non-job-title entries from qualifications
        if not is_job_title(norm):
            base_skills_clean.append(norm)
    # base_skills_raw → store original_skills as-is for audit
    original_skills_str = "|".join(normalize_skill(s).upper() for s in base_skills_raw if s)

    # Extract from job title + description using full vocabulary
    dynamic = extract_skills_from_text(f"{job}\n{desc}", vocab)

    # Merge: base (non-title) + dynamic
    merged_lower = set()
    for s in base_skills_clean:
        merged_lower.add(s.lower())
    for s in dynamic:
        merged_lower.add(s.lower())

    # Build self-referential token set — skills matching the hiring company's
    # own name are blocked for that row (Notion shouldn't list Notion as a skill)
    self_tokens = company_self_tokens(company)

    # Validate and split into graph-matched vs unmatched
    validated = []
    unmatched = []

    for skill_lower in sorted(merged_lower):
        if not is_valid_skill_label(skill_lower):
            continue
        # Drop skills that are just the company's own name/product
        if skill_lower in self_tokens:
            continue
        graph_match = validate_against_graph(skill_lower, concept_lookup, all_concepts_lower)
        if graph_match:
            validated.append(graph_match)
        else:
            # Keep unmatched skills that pass quality checks — they may be
            # real emerging skills not yet in the graph
            display = skill_lower.upper()
            if is_valid_skill_label(display):
                unmatched.append(display)

    # Deduplicate and cap
    validated = sorted(set(validated))[:MAX_SKILLS_PER_ROW]
    unmatched = sorted(set(unmatched))[:MAX_SKILLS_PER_ROW]

    # Canonical output form: uppercase for display consistency
    validated_upper = [v.upper() for v in validated]

    out = dict(row)
    out.pop("description", None)
    out["company"] = company
    out["job"] = job
    out["original_skills"] = original_skills_str
    out["normalized_skills"] = "|".join(validated_upper)
    out["unmatched_skills"] = "|".join(unmatched)
    out["skill_count"] = str(len(validated_upper))
    out["is_noise_row"] = "1" if is_noise_row(company, job, desc) else "0"
    return out


# =============================================================================
# STATS REPORTER
# =============================================================================
def print_stats(rows: list[dict]) -> None:
    counts = [int(r.get("skill_count", 0)) for r in rows]
    non_noise = [r for r in rows if r.get("is_noise_row") != "1"]
    counts_clean = [int(r.get("skill_count", 0)) for r in non_noise]

    total = len(rows)
    noise = sum(1 for r in rows if r.get("is_noise_row") == "1")
    zero_skills = sum(1 for c in counts_clean if c == 0)
    one_skill = sum(1 for c in counts_clean if c == 1)

    if counts_clean:
        avg = sum(counts_clean) / len(counts_clean)
        mx = max(counts_clean)
        mn = min(counts_clean)
    else:
        avg = mx = mn = 0

    print(f"\n{'-'*50}")
    print(f"Total rows        : {total}")
    print(f"Noise rows        : {noise}")
    print(f"Clean rows        : {len(non_noise)}")
    print(f"Rows with 0 skills: {zero_skills}")
    print(f"Rows with 1 skill : {one_skill}  (should be near 0 after fix)")
    print(f"Avg skills/row    : {avg:.1f}")
    print(f"Min / Max skills  : {mn} / {mx}")

    # Top-25 skills across all rows
    from collections import Counter
    skill_counter: Counter = Counter()
    for r in non_noise:
        for skill in r.get("normalized_skills", "").split("|"):
            skill = skill.strip()
            if skill:
                skill_counter[skill] += 1

    print(f"\nTop 25 skills across all rows:")
    for skill, cnt in skill_counter.most_common(25):
        bar = "#" * min(cnt, 40)
        print(f"  {skill:<40s} {cnt:3d}  {bar}")

    # Unmatched skills summary
    unmatched_counter: Counter = Counter()
    for r in non_noise:
        for skill in r.get("unmatched_skills", "").split("|"):
            skill = skill.strip()
            if skill:
                unmatched_counter[skill] += 1

    if unmatched_counter:
        print(f"\nTop 20 unmatched skills (not in graph -- consider adding):")
        for skill, cnt in unmatched_counter.most_common(20):
            print(f"  {skill:<40s} {cnt:3d}")

    print(f"{'-'*50}\n")


# =============================================================================
# MAIN
# =============================================================================
def main():
    parser = argparse.ArgumentParser(description="Normalize LinkedIn scrape CSV for tuning")
    parser.add_argument("--in", dest="in_path", default="in.csv")
    parser.add_argument("--out", dest="out_path", default="out.csv")
    parser.add_argument("--drop-noise", action="store_true", help="Drop rows flagged as noise")
    parser.add_argument("--stats-only", action="store_true", help="Print stats from existing out.csv without re-processing")
    args = parser.parse_args()

    script_dir = Path(__file__).parent
    in_path = Path(args.in_path)
    out_path = Path(args.out_path)

    if args.stats_only:
        if not out_path.exists():
            raise FileNotFoundError(f"No output file found at {out_path}")
        with open(out_path, newline="", encoding="utf-8") as f:
            rows = list(csv.DictReader(f))
        print_stats(rows)
        return

    if not in_path.exists():
        raise FileNotFoundError(f"Input CSV not found: {in_path}")

    # Load concepts vocabulary
    extractable_concepts, all_concepts = load_concepts(script_dir)

    # Build extraction vocabulary
    vocab = build_vocab(extractable_concepts)
    print(f"Extraction vocabulary size: {len(vocab)} terms")

    # Build concept lookup for validation
    concept_lookup = build_concept_lookup(all_concepts)
    all_concepts_lower = list(concept_lookup.keys())
    print(f"Graph concept lookup size : {len(concept_lookup)} concepts")
    if not _FUZZY_AVAILABLE:
        print("WARNING: thefuzz not installed — fuzzy matching disabled (exact only)")

    # Load input
    with open(in_path, newline="", encoding="utf-8") as f:
        rows = list(csv.DictReader(f))
    print(f"Input rows: {len(rows)}")

    # Normalize
    normalized_rows = [
        normalize_row(row, vocab, concept_lookup, all_concepts_lower)
        for row in rows
    ]

    if args.drop_noise:
        normalized_rows = [r for r in normalized_rows if r.get("is_noise_row") != "1"]

    # Determine output columns
    all_columns: set[str] = set()
    for row in normalized_rows:
        all_columns.update(row.keys())
    all_columns.discard("description")

    preferred = [
        "company", "job", "job_type",
        "original_skills", "normalized_skills", "unmatched_skills",
        "skill_count", "is_noise_row",
    ]
    fieldnames = (
        [c for c in preferred if c in all_columns]
        + sorted(c for c in all_columns if c not in preferred)
    )

    with open(out_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(normalized_rows)

    print(f"Output rows: {len(normalized_rows)}")
    print(f"Written    : {out_path}")

    print_stats(normalized_rows)


if __name__ == "__main__":
    main()
